In [3]:
# write your code here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline

#import a dataset
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/teleCust1000t.csv')
df.head()
#check the value caounts of the dependent variable that one wants to predict.
df['custcat'].value_counts()

#convert Pandas dataframe to numpy array
X = df[['region', 'tenure','age', 'marital', 'address', 'income', 'ed', 'employ','retire', 'gender', 'reside']].values

#define y the column that one wants to predict
y= df['custcat'].values

#Normalize the data 
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

#Train Test split - split the dataset.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 4)
print('Train set:', X_train.shape, y_train.shape)
print('Test set:', X_test.shape, y_test.shape)

#------Classification--------
from sklearn.neighbors import KNeighborsClassifier
k= 4
#Train model and predict
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train, y_train)
neigh

#Predict the test set
yhat = neigh.predict(X_test)
yhat
xhat = neigh.predict(X_train)
xhat

#Evalute accuracy
from sklearn import metrics
print("Train set accuracy: ", metrics.accuracy_score(y_train, xhat))
print("Test set accuracy: ", metrics.accuracy_score(y_test, yhat))

k=6
neigh6 = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat6 = neigh6.predict(X_test)
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh6.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat6))

Train set: (800, 11) (800,)
Test set: (200, 11) (200,)
Train set accuracy:  0.5475
Tes set accuracy:  0.32
Train set Accuracy:  0.51625
Test set Accuracy:  0.31


In [9]:
yhat.shape[0]
yhat==y_test



array([0.3  , 0.29 , 0.315, 0.32 , 0.315, 0.31 , 0.335, 0.325, 0.34 ])

In [16]:
Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
print(mean_acc)
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc


[0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0.3  , 0.29 , 0.315, 0.32 , 0.315, 0.31 , 0.335, 0.325, 0.34 ])

In [1]:
#Plot model accuracy for different number of ks

plt.plot(range(1,Ks),mean_acc,'g')
plt.fill_between(range(1,Ks),mean_acc - 1 * std_acc,mean_acc + 1 * std_acc, alpha=0.10)
plt.fill_between(range(1,Ks),mean_acc - 3 * std_acc,mean_acc + 3 * std_acc, alpha=0.10,color="green")
plt.legend(('Accuracy ', '+/- 1xstd','+/- 3xstd'))
plt.ylabel('Accuracy ')
plt.xlabel('Number of Neighbors (K)')
plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [15]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1) 

The best accuracy was with 0.34 with k= 9
